import {ens_roll, Mesh, MeshPresets, rm_sieve_loot, SieveRecipeBuilder} from "../lib/exnihilo_sieve";
import {rankine} from "../lib/ids";

export function run_early_server(event: KRecipeEvent) {
    removal(event);
    overrides(event);
    create(event);
}




function create(event: KRecipeEvent) {
    new SieveRecipeBuilder()
        .set_input("a", "exnihilosequentia:crushed_andesite")
        .set_input("d", "exnihilosequentia:crushed_diorite")
        .set_input("g", "exnihilosequentia:crushed_granite")
        .set_input("v", "minecraft:gravel")
        .add_output("dv", rankine("petalite"), MeshPresets.ore(0.05))
        .add_output("gdv", rankine("malachite"), MeshPresets.ore(0.2))
        .add_output("gv", rankine("azurite"), MeshPresets.ore(0.15))
        .add_output("gav", rankine("chalcopyrite"), MeshPresets.ore(0.12))
        .add_output("d", rankine("lepidolite"), MeshPresets.ore(0.03))
        .add_output("dvga", rankine("cassiterite"), MeshPresets.ore(0.3))
        .add_output("dg", rankine("alumina"), MeshPresets.ore(0.21))
        .add_output("ag", rankine("sphalerite"), MeshPresets.ore(0.05))
        .add_output("vgda", rankine("magnetite"), MeshPresets.ore(0.34))
        .add_output("ad", rankine("pentlandite"), MeshPresets.ore(0.18))
        .add_output("v", rankine("magnesite"), MeshPresets.ore(0.23))
        .add_output("avg", rankine("galena"), MeshPresets.ore(0.23))
        .add_output("ad", rankine("vanadinite"), MeshPresets.ore(0.31))
        .add_output("gv", rankine("bismuthinite"), MeshPresets.ore(0.2))
        .add_output("gd", rankine("acanthite"), MeshPresets.ore(0.14))
        .add_output("gv", rankine("pyrolusite"), MeshPresets.ore(0.14))
        .add_output("dva", rankine("chromite"), MeshPresets.ore(0.09))
        .add_output("dva", rankine("moplybdenite"), MeshPresets.ore(0.09))
        .add_output("dva", rankine("wolframite"), MeshPresets.ore(0.09))
        .add_output("dva", rankine("ilmenite"), MeshPresets.ore(0.06))
        .add_output("dvg", rankine("columbite"), MeshPresets.ore(0.05))
        .add_output("ad", rankine("tantalite"), MeshPresets.ore(0.06))
        .add_output("gv", rankine("cobaltite"), MeshPresets.ore(0.09))
        .add_output("gv", rankine("celestine"), MeshPresets.ore(0.1))
        .add_output("gv", rankine("platinum_arsenide"), MeshPresets.ore(0.04))
        .add_output("gdv", rankine("zircon"), MeshPresets.ore(0.08))
        .add_output("gv", rankine("thorite"), MeshPresets.ore(0.07))
        .add_output("gva", rankine("uraninite"), MeshPresets.ore(0.1))
        .add_output("vad", rankine("greenockite"), MeshPresets.ore(0.15))
        .add_output("va", rankine("stibnite"), MeshPresets.ore(0.3))
        .add_output("d", rankine("xenotime"), MeshPresets.ore(0.02))
        .add_output("dv", rankine("barite"), MeshPresets.ore(0.1))
        .add_output("dva", rankine("cryolite"), MeshPresets.ore(0.23))
        .add_output("a", rankine("cerium_monazite"), MeshPresets.ore(0.02))
        .add_output("a", rankine("lanthanum_monazite"), MeshPresets.ore(0.02))
        .add_output("a", rankine("neodymium_monazite"), MeshPresets.ore(0.02))
        .add_output("a", rankine("samarium_monazite"), MeshPresets.ore(0.02))
        .add_output("vgad", rankine("lignite"), MeshPresets.ore(0.4))
        .add_output("vgad", rankine("subbituminous_coal"), MeshPresets.ore(0.24))
        .add_output("vgd", rankine("bituminous_coal"), MeshPresets.ore(0.26))
        .add_output("vg", rankine("anthracite_coal"), MeshPresets.ore(0.26))
        .add_output("vgda", rankine("salt"), MeshPresets.ore(0.4))
        .add_output("vga", rankine("pink_salt"), MeshPresets.ore(0.35))
        .add_output("a", rankine("graphite"), MeshPresets.ore(0.2))
        .add_output("a", rankine("silicon_carbide"), MeshPresets.ore(0.2))
        .add_output("gv", rankine("cinnabar"), MeshPresets.ore(0.4))
        .add_output("ad", rankine("ruby"), MeshPresets.ore(0.1))
        .add_output("ad", rankine("sapphire"), MeshPresets.ore(0.1))
        .add_output("ad", rankine("opal"), MeshPresets.ore(0.1))
        .add_output("ad", rankine("aquamarine"), MeshPresets.ore(0.1))
        .add_output("ad", rankine("tourmaline"), MeshPresets.ore(0.1))
        .add_output("ad", rankine("tiger_iron"), MeshPresets.ore(0.1))
        .add_output("ad", rankine("garnet"), MeshPresets.ore(0.1))
        .add_output("ad", rankine("peridot"), MeshPresets.ore(0.1))
        .add_output("ad", rankine("topaz"), MeshPresets.ore(0.1))
        .add_output("ad", rankine("amber"), MeshPresets.ore(0.1))
        .add_output("ad", rankine("pearl"), MeshPresets.ore(0.1))
        .add_output("ad", rankine("fluorite"), MeshPresets.ore(0.1))
        .add_output("ad", rankine("labradorite"), MeshPresets.ore(0.1))
        .add_output("ad", rankine("lonsdaleite_diamond"), MeshPresets.ore(0.1))
        .add_output("ad", rankine("rhodonite"), MeshPresets.ore(0.1))
        .add_output("ad", rankine("rhodochrosite"), MeshPresets.ore(0.1))
        .add_output("ad", rankine("chrome_enstatite"), MeshPresets.ore(0.1))
        .add_output("ad", rankine("feldspar"), MeshPresets.ore(0.1))
        .add_output("ad", rankine("plagioclase_feldspar"), MeshPresets.ore(0.1))
        .add_output("d", rankine("calcite"), MeshPresets.ore(0.1))
        .add_output("ad", rankine("dolomite"), MeshPresets.ore(0.1))
        .add_output("gv", rankine("olivine"), MeshPresets.ore(0.1))
        .add_output("dv", rankine("pyroxene"), MeshPresets.ore(0.1))
        .add_output("a", rankine("mica"), MeshPresets.ore(0.1))
        .add_output("a", rankine("amphibole"), MeshPresets.ore(0.1))
        .add_output("a", rankine("calcium_silicate"), MeshPresets.ore(0.2))
        .add_output("d", rankine("pozzolan"), MeshPresets.ore(0.2))
        .add_output("ag", rankine("perlite"), MeshPresets.ore(0.08))
        .add_output("gd", rankine("trona"), MeshPresets.ore(0.08))
        .add_output("gv", rankine("thenardite"), MeshPresets.ore(0.1))
        .add_output("d", rankine("borax"), MeshPresets.ore(0.08))
        .add_output("d", rankine("saltpeter"), MeshPresets.ore(0.08))
        .build(event);
}


function removal(event: KRecipeEvent) {
    rm_sieve_loot(event, 'emerald')
    rm_sieve_loot(event, 'diamond')
    rm_sieve_loot(event, 'piece_aluminum_gravel')
    rm_sieve_loot(event, 'piece_copper_gravel')
    rm_sieve_loot(event, 'piece_gold_crushed_netherrack')
    rm_sieve_loot(event, 'piece_gold_gravel')
    rm_sieve_loot(event, 'piece_iron_gravel')
    rm_sieve_loot(event, 'piece_iron_sand')
    rm_sieve_loot(event, 'piece_lead_gravel')
    rm_sieve_loot(event, 'piece_nickel_gravel')
    rm_sieve_loot(event, 'piece_platinum_gravel')
    rm_sieve_loot(event, 'piece_silver_gravel')
    rm_sieve_loot(event, 'piece_tin_gravel')
    rm_sieve_loot(event, 'piece_uranium_gravel')
    rm_sieve_loot(event, 'piece_zinc_gravel')
    rm_sieve_loot(event, 'piece_osmium_gravel')
    event.remove({id: 'exnihilomekanism:sieve/ens_piece_osmium_1'})
    event.remove({id: 'exnihilomekanism:sieve/ens_piece_osmium_2'})
    event.remove({id: 'exnihilomekanism:sieve/ens_piece_osmium_3'})
    event.remove({id: 'exnihilothermal:sieve/ens_apatite'})
    event.remove({id: 'exnihilothermal:sieve/ens_cinnabar'})
    event.remove({id: 'exnihilothermal:sieve/ens_niter'})
    event.remove({id: 'exnihilothermal:sieve/ens_sulfur'})
}


function overrides(event: KRecipeEvent) {

}
